### ISSUE TITLE
error reading fst files on Windows??

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/addNlcdData#4]
On windows, with certain files, we get the error:

```r
Error in fst::read_fst(path = nlcd_file, from = nlcd_row, to = nlcd_row,  : It seems the file header was damaged or incomplete
```

Cannot reproduce on other machines, maybe a Windows issue?  But other nlcd files work OK.

**Comment by cole-brokamp** [comment]
This is related to which method `download.file` uses.  It seems that one of the methods on Windows changes the file header making a `fst` file unreadable.

We need to test if this is still a problem on the `s3` package since it uses a different API to download files.

**Comment by erikarasnick** [comment]
updated to use `s3` so this should be fixed.
